version: "3.8"
services:
  async_service:
    build:
      context: .
      target: production
    environment:
      - PORT_APP=3000
      - WORKERS=2
      - HOST_APP=0.0.0.0
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      elastic:
        condition: service_healthy
      redis:
        condition: service_healthy

  elastic:
    image: elasticsearch:7.7.0
    environment:
      cluster.name: movies-elasticsearch-cluster
      network.host: 0.0.0.0
      bootstrap.memory_lock: "true"
      discovery.type: single-node
    healthcheck:
      test: curl -s http://elastic:9200/_cat/health >/dev/null || exit 1
      interval: 5s
      timeout: 20s
      retries: 100
    volumes:
      - data_es:/usr/share/elasticsearch/data
    ulimits:
      memlock:
        soft: -1
        hard: -1
    expose:
      - 9200

  redis:
    image: redis:6-alpine
    volumes:
      - data_redis:/data
    ports:
      - "6379:6379"
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 20s
      retries: 2
    restart: always


  nginx:
    image: nginx:1.19.2
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/configs:/etc/nginx/conf.d:ro
    depends_on:
      - async_server
    ports:
      - "80:80"


volumes:
  data_redis:
    driver: "local"
  data_es:
    driver: "local"
